/**
 * Modern AI Text Detection View (2025 iOS Design)
 */

import { useEffect, useRef } from 'react';
import { Button } from './Button';
import { Card, CardHeader, CardContent } from './Card';
import { ModelSelector } from './ModelSelector';
import { useAIDetection } from '../hooks/useAIDetection';
import { useModels } from '../hooks/useModels';
import { cn } from '../lib/utils';

interface AIDetectViewProps {
  text: string;
  setText: (text: string) => void;
  analyzing: boolean;
  setAnalyzing: (analyzing: boolean) => void;
}

export function AIDetectView({ text, setText, analyzing, setAnalyzing }: AIDetectViewProps) {
  const { result, isAnalyzing, error, analyzeText, stopAnalysis, clearResult } = useAIDetection();
  const { models, currentModel, loadModel } = useModels();
  const autoLoadAttemptedRef = useRef(false);

  // Auto-load a recommended AI detector if none is loaded (only once)
  useEffect(() => {
    const loadDefaultDetector = async () => {
      // Only attempt auto-load once
      if (autoLoadAttemptedRef.current) {
        return;
      }
      
      // Wait for models to be loaded
      if (models.length === 0) {
        return;
      }
      
      // Filter for AI detector models
      const detectors = models.filter(m => m.model_type === 'ai_detector');
      
      // Check if we need to load a detector
      const currentModelInfo = models.find(m => m.name === currentModel);
      const needsDetector = !currentModel || currentModelInfo?.model_type !== 'ai_detector';
      
      if (needsDetector && detectors.length > 0) {
        // Mark that we've attempted to load
        autoLoadAttemptedRef.current = true;
        
        // Find recommended detector or first available
        const recommended = detectors.find(m => m.recommended && m.available);
        const fallback = detectors.find(m => m.available);
        const modelToLoad = recommended || fallback;
        
        if (modelToLoad) {
          console.log('Auto-loading AI detector:', modelToLoad.name);
          await loadModel(modelToLoad.name);
        }
      } else if (!needsDetector) {
        // Already have a detector loaded, mark as attempted
        autoLoadAttemptedRef.current = true;
      }
    };

    loadDefaultDetector();
  }, [models, currentModel, loadModel]);

  // Sync analyzing state with parent
  useEffect(() => {
    setAnalyzing(isAnalyzing);
  }, [isAnalyzing, setAnalyzing]);

  const handleAnalyze = () => {
    clearResult();
    analyzeText(text, currentModel || undefined);
  };

  const handleStop = () => {
    stopAnalysis();
  };

  return (
    <div className="flex flex-col h-full bg-background">
      {/* Header */}
      <div className="flex justify-between items-start px-6 py-4 bg-card border-b border-border">
        <div className="flex-1">
          <h2 className="text-ios-2xl font-bold text-foreground">AI Text Detection</h2>
          <p className="text-ios-sm text-muted-foreground mt-1">Analyze text to detect AI-generated content</p>
        </div>
        <ModelSelector compact modelType="ai_detector" />
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-4">
        <Card>
          <CardHeader
            title="Analyze Text"
            subtitle="Paste or type text to check if it was generated by AI"
          />
          <CardContent>
            <textarea
              className="w-full min-h-40 px-4 py-3 border border-border rounded-ios-lg bg-background text-ios-base text-foreground resize-none focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary/20 font-sans"
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste text here to analyze..."
              rows={8}
              disabled={analyzing}
            />

            <div className="flex gap-3 mt-4">
              <Button
                variant="secondary"
                onClick={() => {
                  setText('');
                  clearResult();
                }}
                disabled={!text.trim() || isAnalyzing}
              >
                Clear
              </Button>
              {isAnalyzing ? (
                <Button
                  variant="danger"
                  onClick={handleStop}
                  className="flex-1"
                >
                  Stop
                </Button>
              ) : (
                <Button
                  variant="primary"
                  onClick={handleAnalyze}
                  disabled={!text.trim()}
                  loading={isAnalyzing}
                  className="flex-1"
                >
                  Analyze
                </Button>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Error Display */}
        {error && (
          <Card className="animate-slide-up border-destructive">
            <CardContent>
              <div className="flex items-start gap-3 text-destructive">
                <span className="text-2xl">⚠️</span>
                <div className="flex-1">
                  <h4 className="font-semibold mb-1">Analysis Failed</h4>
                  <p className="text-ios-sm">{error}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Results Display */}
        {result && !error && (
          <Card className="animate-slide-up">
            <CardHeader
              title="Detection Results"
              subtitle={`Analyzed ${result.textLength} characters in ${result.processingTime.toFixed(2)}s`}
            />
            <CardContent className="space-y-4">
              {/* Main Result */}
              <div className={cn(
                "flex items-center justify-between p-4 rounded-ios-lg border-2",
                result.isAIGenerated 
                  ? "bg-destructive/10 border-destructive" 
                  : "bg-green-50 dark:bg-green-950 border-green-500"
              )}>
                <div className="flex items-center gap-3">
                  <span className="text-4xl">{result.isAIGenerated ? '🤖' : '👤'}</span>
                  <div>
                    <h3 className="text-ios-lg font-bold">
                      {result.isAIGenerated ? 'AI-Generated' : 'Human-Written'}
                    </h3>
                    <p className="text-ios-sm opacity-80">
                      {(result.confidence * 100).toFixed(1)}% confidence
                    </p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-ios-2xl font-bold">
                    {(result.confidence * 100).toFixed(0)}%
                  </div>
                </div>
              </div>

              {/* Probability Breakdown */}
              <div className="space-y-3">
                <h4 className="text-ios-base font-semibold text-foreground">Probability Breakdown</h4>
                
                {/* AI Probability Bar */}
                <div>
                  <div className="flex justify-between text-ios-sm mb-1">
                    <span className="text-muted-foreground">AI-Generated</span>
                    <span className="font-semibold">{(result.aiProbability * 100).toFixed(1)}%</span>
                  </div>
                  <div className="h-3 bg-secondary rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-destructive transition-all duration-500"
                      style={{ width: `${result.aiProbability * 100}%` }}
                    />
                  </div>
                </div>

                {/* Human Probability Bar */}
                <div>
                  <div className="flex justify-between text-ios-sm mb-1">
                    <span className="text-muted-foreground">Human-Written</span>
                    <span className="font-semibold">{(result.humanProbability * 100).toFixed(1)}%</span>
                  </div>
                  <div className="h-3 bg-secondary rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-green-500 transition-all duration-500"
                      style={{ width: `${result.humanProbability * 100}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Metadata */}
              <div className="grid grid-cols-2 gap-3 pt-3 border-t border-border">
                <div>
                  <p className="text-ios-xs text-muted-foreground mb-1">Model</p>
                  <p className="text-ios-sm font-medium truncate">{result.model}</p>
                </div>
                <div>
                  <p className="text-ios-xs text-muted-foreground mb-1">Method</p>
                  <p className="text-ios-sm font-medium">{result.detectionMethod}</p>
                </div>
                <div>
                  <p className="text-ios-xs text-muted-foreground mb-1">Text Length</p>
                  <p className="text-ios-sm font-medium">{result.textLength} chars</p>
                </div>
                <div>
                  <p className="text-ios-xs text-muted-foreground mb-1">Processing Time</p>
                  <p className="text-ios-sm font-medium">{result.processingTime.toFixed(3)}s</p>
                </div>
              </div>

              {/* Disclaimer */}
              <div className="pt-3 border-t border-border">
                <p className="text-ios-xs text-muted-foreground italic">
                  ⚠️ Note: AI detection is not 100% accurate. Results should be used as guidance, not definitive proof.
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Empty State */}
        {!result && !error && !isAnalyzing && (
          <Card className="animate-fade-in">
            <CardContent>
              <div className="flex flex-col items-center text-center py-8">
                <div className="text-5xl mb-4 opacity-60">🔍</div>
                <h3 className="text-ios-xl font-semibold text-foreground mb-2">Ready to Analyze</h3>
                <p className="text-ios-sm text-muted-foreground mb-4">
                  Paste text above and click "Analyze" to detect AI-generated content
                </p>
                <ul className="text-ios-sm text-muted-foreground space-y-2 text-left">
                  <li className="flex items-start gap-2">
                    <span>✓</span>
                    <span>Detect AI-generated text with high accuracy</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span>✓</span>
                    <span>Get confidence scores and detailed analysis</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span>✓</span>
                    <span>Support for multiple detection models</span>
                  </li>
                </ul>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}

